# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AndalusianPopulation
                                 A QGIS plugin
 This plugin allows easier access to information about the population of Andalusia (region of Spain)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-01
        copyright            : (C) 2021 by devmemi
        email                : devmemi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AndalusianPopulation class from file AndalusianPopulation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Andalusian_Population import AndalusianPopulation
    return AndalusianPopulation(iface)
